name: llm_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.6
  - protobuf>=3.20.0
  - accelerate
  - sentencepiece
  - huggingface_hub
  - jinja2>=3.1.0
  - pip
  - ipykernel
  - pandas
  - pip:
      - transformers>=4.51.0

